hasCJKLanguage = true
baseurl = "https://ie.u-ryukyu.ac.jp/~kono/hugo/"  # Include trailing slash
title = "home"
copyright = "Copyright © 2021-2023"
# canonifyurls = true
paginate = 10
theme = "ie-hugo-theme"
drafts = false
enableRobotsTXT = true
[languages]
  [languages.en]
    title = "Your Website Title in English"
    languageName = "English"
    contentDir = "content/en"
    weight = 1
  [languages.ja]
    title = "Your Website Title in Japanese"
    languageName = "日本語"
    contentDir = "content/ja"
[params]
  description = "This is a multilingual Hugo site"
  author = "Author Name"
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    identifier = "hugo"
    name = "Hugo"
    url = "/"
    weight = 20
[permalinks]
    section = "/:sections/:title/"
[frontmatter]
   date                       = [ "date", ":filename", ":default"]
   publishDate                = [ "publishDate", "date"]
   lastmod                    = [ "lastmod", ":fileModTime", "publishDate"]
   expiryDate                 = [ "expiryDate"]
